"""Financial AI Copilot — Agent Package."""

from fin_agent.memory import get_mongo_collection, vector_search
from fin_agent.prompts import ORCHESTRATOR_INSTRUCTIONS
from fin_agent.sandbox import FinancialSandbox, run_financial_analysis
from fin_agent.tools import (
    calculate_financial_metrics,
    compute_population_stability_index,
    download_dataset,
    delete_dataset,
    generate_sample_financial_dataset,
    get_experiment_leaderboard,
    get_pipeline_state,
    list_available_datasets,
    list_findings,
    load_dataset_info,
    run_code,
    run_script,
    save_experiment_result,
    save_finding,
    save_pipeline_step,
    save_to_memory,
    search_memory,
    save_report,
    publish_artifact,
    sync_artifacts_panel,
    think_tool,
    update_pipeline_step_status,
    push_model_leaderboard,
    set_investigation_context,
    store_charts,
)

__all__ = [
    "ORCHESTRATOR_INSTRUCTIONS",
    "think_tool",
    "load_dataset_info",
    "list_available_datasets",
    "generate_sample_financial_dataset",
    "save_finding",
    "list_findings",
    "save_experiment_result",
    "get_experiment_leaderboard",
    "calculate_financial_metrics",
    "compute_population_stability_index",
    "run_code",
    "run_script",
    "download_dataset",
    "delete_dataset",
    "save_pipeline_step",
    "get_pipeline_state",
    "save_to_memory",
    "search_memory",
    "save_report",
    "publish_artifact",
    "sync_artifacts_panel",
    "update_pipeline_step_status",
    "push_model_leaderboard",
    "set_investigation_context",
    "store_charts",
    "get_mongo_collection",
    "vector_search",
    "FinancialSandbox",
    "run_financial_analysis",
]
